### PR TITLE
feat(conf): add all catppuccin themes, split config

### PR DESCRIPTION
**Pull request by vinnyA3**
## Description

* add all catppuccin themes to separate config files
* update readme to include word on choosing out your desired theme

## Resolves

- [#10](https://github.com/catppuccin/tmux/issues/10)

## Visual Reference

The following screenshots display different tmux modes/states (from top left, in clockwise rotation: prefix input, copy mode, clock, command mode):

**Latte**
latte

**Frappe**
frappe

**Macchiato**
macchiato

**Mocha**
mocha

### CODE REVIEW

**Comment by vinnyA3** [comment]
@Pocco81  - let me know if there are palette modifications that should be made!

**Comment by andreasgrafen** [comment]
Heya, just chiming in real quick.
Thanks for adding the Latte colours to the config. Preferably we would have seperate config files the user can chose from that have the seperate themes.

In parallel to this: Would you also be interested in maybe updating the Mocha palette as well as also adding in Macchiato and Frappe? c:

**Comment by vinnyA3** [comment]
@andreasgrafen sure! can do.  I'll separate the config file as well 👍🏽

**Comment by vinnyA3** [comment]
updated!

**Comment by her** [comment]
Can we merge this pretty please? 💅

**Comment by hsheikhali1P** [comment]
@vinnyA3 @andreasgrafen Are you both waiting for anyone to have this merged?

**Comment by vinnyA3** [comment]
@hsheikhali1P yeap! waiting on a review+merge by someone w/ write access

cc @Pocco81 - for visibility

**Comment by jaredmcqueen** [comment]
paging @Pocco81

**Comment by nekowinston** [comment]
I'll have a look at this, since I got write access as well.

**Comment by nekowinston** [comment]
I've had a look at it, and this seems like a great start! I'll also give TPM a shot, maybe with a global setting to toggle the parent/current directory setting. Thanks a lot, sorry for the long wait!

**Comment by nekowinston** [comment]
I totally forgot about this, @vinnyA3 - if you want to be added to the "Thanks to" section on the README, you could open a PR, or just lemme know how you'd like to be credited, and I'll add it.

**Comment by vinnyA3** [comment]
oo cool .. sure thing, i'll open a PR, thanks!! @nekowinston

**Pull request merged**
