### PR TITLE
Add config options

### PR DESCRIPTION
**Pull request by ervinpopescu**
`@catppuccin_window_left_separator_inverse`
`@catppuccin_window_right_separator_inverse`
`@catppuccin_status_left_separator_inverse`

Bonus: `shfmt`.

### CODE REVIEW

**Comment by ervinpopescu** [comment]
The config:
```tmux
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_left_separator_inverse "yes"
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_right_separator_inverse "no"
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_left_separator_inverse "no"
set -g @catppuccin_status_right_separator_inverse "yes"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_modules_right "application session host battery date_time"
set -g @catppuccin_status_modules_left ""
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"


```

The result:
image

**Comment by 89iuv** [comment]
Merged the PR. Looks good. One small request is if you can update the documentation with the new options.

**Comment by AlexNabokikh** [comment]
This broke the existing config for me.

**Comment by AlexNabokikh** [comment]
The change also breaks all the demo configs from the README. 
image

**Comment by 89iuv** [comment]
I have reverted the PR because of the issues discovered.

**Comment by ervinpopescu** [comment]
Oof. I guess I did not test properly. Will try to do some more debugging.

**Pull request merged**
