### PR TITLE
Window connect separator 

### PR DESCRIPTION
**Pull request by sukhostavets**
Issue: #177

### CODE REVIEW

**Comment by vdbe** [comment]
There seems to be an issue with the background between the windows

`set -g @catppuccin_status_background "#ff0000"` with config:
- provided in #177 
Screenshot from 2024-04-08 10-57-19

- [config 2](https://github.com/catppuccin/tmux#config-2)
Screenshot from 2024-04-08 10-56-45

- [config 3](https://github.com/catppuccin/tmux#config-3)
Screenshot from 2024-04-08 10-55-35

**Comment by vdbe** [comment]
I think you need to set `window-status-style` bg (and prbly also the active style) like done with `status-style` to get default working.

https://github.com/catppuccin/tmux/blob/5ed4e8a6a20c928688da268dfcdf460ac9c3cb49/catppuccin.tmux#L56-L65

**Comment by MykhailoSukhostavets** [comment]
Thank you, I will test it later.
(Also I still need to update logic when we fill number)

**Comment by MykhailoSukhostavets** [comment]
> I think you need to set `window-status-style` bg (and prbly also the active style) like done with `status-style` to get default working.

Didn't work or I did smth wrong, I tried to play with logic like that:
```
      set-window-option -g window-status-style fg="#ff0000"
      set-window-option -g window-status-style bg="#ff0000"
      set-window-option -g window-status-current-style fg="#ff0000"
      set-window-option -g window-status-current-style bg="#ff0000"
```

Other than "default" should work fine
image

**Comment by vdbe** [comment]
Is there _any_ possibility to reduce the line count of `build_window_format` it was bad before but this a 100 line switch statement with 4 almost identical cases/branches

Some patterns (for window_connect_seperator blocks):
- bg consists 1 color and default (always at the same place)
- first 2 show_left always `$thm_bg`

**Comment by vdbe** [comment]
https://github.com/catppuccin/tmux/blob/33c4fd62df96b39cec2b2c08bc341c88d9392761/builder/window_builder.sh#L52

bg needs to be `default` for connected and `$background` for not connected

**Pull request closed without merging**
