### PR TITLE
feat(ui): make the separator configurable

### PR DESCRIPTION
**Pull request by 89iuv**
Added a way to configure the separator. 
The default behavior is to use the rounded separator. 
Updated the documentation as well.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Awesome work on this @89iuv. I think this PR and #32 are doing similar things. Let me think about how combine this work if possible so everyone can be credited for this customization.

**Comment by rogeruiz** [comment]
Hey @89iuv, let me know if you need any help refactoring your PR after #29 has been merged in.

**Comment by rkarish** [comment]
Hi @89iuv, I can also help with refactoring if needed!

**Comment by 89iuv** [comment]
rework done in: https://github.com/catppuccin/tmux/pull/30

**Pull request closed without merging**
